Repository nka21/CodeRush, pull requests merged in 2025-07, with the labels that each got.

#88 バックエンドの`.keep`ファイルを削除
  server/.keep
Labels: ♻️ リファクタリング, ⚙️ バックエンド

#93 ホーム画面のデザイン刷新とプレイ画面の追加
  client/app/_components/HomeClient.tsx
  client/app/globals.css
  client/app/layout.tsx
  client/app/page.tsx
  client/app/test/_components/AnswerChoice.tsx
  client/app/test/_components/CodeDisplay.tsx
  client/app/test/_components/QuizGameClient.tsx
  client/app/test/_components/QuizResult.tsx
  client/app/test/_components/QuizTimerSection.tsx
  client/app/test/_components/TimerProgressBar.tsx
  client/app/test/_constants/quiz.ts
  client/app/test/_data/mock.json
  client/app/test/_types/quiz.ts
  client/app/test/page.tsx
  client/components/Button.tsx
  client/components/Modal.tsx
  client/components/RoomButton.tsx
  client/components/TerminalLayout.tsx
  client/hooks/useQuizTimer.ts
  client/hooks/useTypingAnimation.ts
Labels: ♻️ リファクタリング, ✨ 新機能, 🎨 UI改善, 🖥️ フロントエンド

#92 websocket通信の追加
  server/mock/db.json
  server/src/cmd/route/main.go
  server/src/go.mod
  server/src/go.sum
  server/src/internal/feature/quiz/handler/quizHandler.go
  server/src/internal/feature/quiz/route.go
  server/src/internal/feature/quiz/types/message.go
  server/src/internal/feature/quiz/websocket/client.go
  server/src/internal/feature/quiz/websocket/hub.go
  server/src/internal/feature/room/route.go
  server/src/internal/feature/room/service/roomService.go
Labels: 🔥 優先度: 高, ⚙️ バックエンド

#100 作成と参加から待機画面に遷移するまでのAPI通信を実装
  client/app/_components/HomeClient.tsx
  client/app/_types/api.ts
  client/app/_utils/api.ts
  client/app/room/[roomId]/page.tsx
  client/app/room/_components/RoomClient.tsx
  client/hooks/api/useCreateRoom.ts
  client/hooks/api/useJoinRoom.ts
  client/package.json
  client/pnpm-lock.yaml
Labels: ✨ 新機能, 🖥️ フロントエンド

#99 Feature/82/quiz broadcast
  server/mock/db.json
  server/src/cmd/route/main.go
  server/src/internal/feature/quiz/handler/quizHandler.go
  server/src/internal/feature/quiz/route.go
  server/src/internal/feature/quiz/service/quizService.go
  server/src/internal/feature/quiz/types/quizType.go
  server/src/internal/feature/quiz/websocket/client.go
  server/src/internal/feature/quiz/websocket/hub.go
  server/src/internal/feature/room/service/roomService.go
Labels: ✨ 新機能, ⚙️ バックエンド

#98 quiz-resultの結果画面のUI変更
  client/app/test/_components/QuizGameClient.tsx
  client/app/test/_components/QuizResult.tsx
  client/components/Button.tsx
  client/pnpm-lock.yaml
Labels: 🎨 UI改善, 🔥 優先度: 高, 🖥️ フロントエンド

#106 Feature/104/create question log page
  client/app/question_log/QuestionLog.tsx
  client/app/question_log/page.tsx
  client/app/test/_components/QuizGameClient.tsx
  client/app/test/_components/QuizResult.tsx
  server/src/internal/feature/quiz/types/message.go
Labels: 🔥 優先度: 高, 🖥️ フロントエンド

#107 hotfix ビルドエラーを解消
  client/app/_components/HomeClient.tsx
  client/app/room/[roomId]/page.tsx
  client/app/room/_components/RoomClient.tsx
  client/app/test/_components/QuizGameClient.tsx
  client/app/test/_components/QuizResult.tsx
  client/components/TerminalLayout.tsx
  client/package.json
  client/pnpm-lock.yaml
Labels: 🐛 バグ, 🔥 優先度: 高

#114 Hostが退出時にルームが削除されるように実装
  server/mock/db.json
  server/src/cmd/route/main.go
  server/src/internal/feature/quiz/websocket/hub.go
Labels: ✨ 新機能, ⚙️ バックエンド

#115 game-start　ボタンをホスト時のみ表示
  client/app/room/_components/RoomClient.tsx
Labels: 🖥️ フロントエンド

#116 ディレクトリ構造のリファクタリング
  client/app/question_log/page.tsx
  client/app/room/[roomId]/_components/QuestionLog.tsx
  client/app/room/[roomId]/_components/ingame/AnswerChoice.tsx
  client/app/room/[roomId]/_components/ingame/CodeDisplay.tsx
  client/app/room/[roomId]/_components/ingame/QuizGameClient.tsx
  client/app/room/[roomId]/_components/ingame/QuizResult.tsx
  client/app/room/[roomId]/_components/ingame/QuizTimerSection.tsx
  client/app/room/[roomId]/_components/ingame/TimerProgressBar.tsx
  client/app/room/[roomId]/_constants/quiz.ts
  client/app/room/[roomId]/_data/mock.json
  client/app/room/[roomId]/_types/quiz.ts
  client/app/room/_components/RoomClient.tsx
  client/app/test/_components/QuizResult.tsx
  client/app/test/page.tsx
  client/hooks/useQuizTimer.ts
Labels: ♻️ リファクタリング, 🔥 優先度: 高, 🖥️ フロントエンド

#120 chore:add_dynamoSettings
  server/src/.gitignore
  server/src/cmd/route/main.go
  server/src/go.mod
  server/src/go.sum
  server/src/internal/database/database.go
  server/src/internal/feature/quiz/websocket/hub.go
  server/src/internal/feature/room/repository/roomRepository.go
  server/src/internal/feature/room/types/roomType.go
Labels: ✨ 新機能, 🔥 優先度: 高, 🔧 環境, ⚙️ バックエンド
